name: Mirror Repository

on:
  push:
    branches: ["**"]
    tags: ["**"]

  workflow_dispatch:   # allow manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history from source (deebanms/React-CN)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # all history, all branches, all tags

      - name: Push mirror to destination (cloudhostingky-alt/React-CN)
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          # Destination repo URL
          DEST_REPO="github.com/cloudhostingky-alt/React-CN.git"

          # Add destination remote with PAT
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@${DEST_REPO}

          # Push everything (branches + tags) to destination
          git push --mirror mirror
