name: Mirror Repository

on:
  push:
    branches: ['**']
    tags: ['**']

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all history and tags

      - name: Debug repo URL
        run: |
          echo "Will push to: https://github.com/cloudhostingky-alt/sms-node.git"

      - name: Push mirror to destination
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          # Add the destination as a remote explicitly (no trailing slash!)
          git remote add mirror https://x-access-token:${MIRROR_TOKEN}@github.com/cloudhostingky-alt/sms-node.git
          
          # Fetch everything from origin
          git fetch --all --tags
          
          # Push everything to mirror (branches + tags)
          git push --mirror mirror
